version: "3.9"

services:
  # Shared PostgreSQL Database
  postgres:
    image: postgres:15.0
    container_name: shared-postgres
    environment:
      POSTGRES_USER: ${SHARED_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${SHARED_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${SHARED_DB_NAME:-maindb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SHARED_DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # User Service
  user-service:
    image: ghcr.io/bechirh/user_management_src:20250611-172941
    container_name: user-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/${SHARED_DB_NAME:-maindb}?currentSchema=user_service"
      SPRING_DATASOURCE_USERNAME: ${SHARED_DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${SHARED_DB_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET:-defaultSecretKey}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
    ports:
      - "8081:8080"

  # Organization Service
  organization-service:
    image: ghcr.io/tarekmestiri/orgmanagement:20250611-171352
    container_name: organization-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/${SHARED_DB_NAME:-maindb}?currentSchema=organization_service"
      SPRING_DATASOURCE_USERNAME: ${SHARED_DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${SHARED_DB_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET:-defaultSecretKey}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
    ports:
      - "8082:8080"

  # Survey Service
  survey-service:
    image: ghcr.io/soussioumaima/surveyservice:20250611-170855
    container_name: survey-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/${SHARED_DB_NAME:-maindb}?currentSchema=survey_service"
      SPRING_DATASOURCE_USERNAME: ${SHARED_DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${SHARED_DB_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET:-defaultSecretKey}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}    # 24h
    ports:
      - "8083:8080"

volumes:
  postgres_data: